### ISSUE TITLE
Requesting libtinfo.so.6 and libm.

### ISSUE THREAD

**Issue by mingodad** [specs-feup/clava#112]
The recently downloaded [`clava.zip`](http://specs.fe.up.pt/tools/clava.zip) dosenst work with Ubuntu 18.04 and probably other systems that only have `libtinfo.so.5` and `GLIBC_2.28`
```
error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```
After installing ncurses-6.3:
```
clang_ast_v12.0.7: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by tmp/clang_ast_exe_mingo/clang_ast_v12.0.7)
clang_ast_v12.0.7: ncurses/lib/libtinfo.so.6: no version information available (required by /tmp/clang_ast_exe_mingo/clang_ast_v12.0.7)
```
And after getting the shared libs installed then I'm getting this error:
```
java.lang.RuntimeException: Exception during interpretation
	at larai.LaraI.execPrivate(LaraI.java:269)
	at larai.LaraI.lambda$3(LaraI.java:221)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.lara.interpreter.exception.WeaverEngineException: exception when initializing the weaver
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:191)
	at larai.LaraI.interpret(LaraI.java:676)
	at larai.LaraI.execPrivate(LaraI.java:256)
	... 5 more
Caused by: pt.up.fe.specs.clang.codeparser.ClavaParserException: There are errors in the source code:
/tmp/clang_ast_exe_mingo/clang_ast_v12.0.7: ncurses/lib/libtinfo.so.6: no version information available (required by /tmp/clang_ast_exe_mingo/clang_ast_v12.0.7)
In file included from clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp:6:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/math.h:300:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/math.h:36:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:310:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/type_traits:420:
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cstddef:44:15: fatal error: 'stddef.h' file not found
#include_next <stddef.h>
              ^~~~~~~~~~
1 error generated.
Error while processing clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp.
In file included from clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp:6:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/math.h:300:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/math.h:36:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:310:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/type_traits:420:
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cstddef:44:15: fatal error: 'stddef.h' file not found
#include_next <stddef.h>
              ^~~~~~~~~~
1 error generated.
Error while processing /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp.

	at pt.up.fe.specs.clang.codeparser.ParallelCodeParser.parse(ParallelCodeParser.java:233)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.createApp(CxxWeaver.java:869)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.createApp(CxxWeaver.java:777)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.begin(CxxWeaver.java:508)
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:174)
	... 7 more
```
```
java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu218.04, mixed mode, sharing)
```

**Comment by mingodad** [comment]
After building ncurses with:
```
./configure --prefix=$HOME/local/ncurses --with-termlib --with-shared --with-versioned-syms
```
This error disappear:
```
/tmp/clang_ast_exe_mingo/clang_ast_v12.0.7: ncurses/lib/libtinfo.so.6: no version information available (required by /tmp/clang_ast_exe_mingo/clang_ast_v12.0.7)
```
But the the `stddef.h` error reamin, probably it's something with the include path but even with extra debug enabled:
```
 -==================================================-
  1. . LARA Options
 -==================================================-
Clava [aspect: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/lara/FullCallGraph.lara, main: , argv: , workspace: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp, workspace_extra: {}, output: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph, include: , autoimportjs: false, external_dependencies: [], tools: [ ] , report: [ ] , metrics: [ ] /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/metrics.json, loc: false, verbose: all, log: [ ] , javascript: false, debug: true, stack trace: true, bundle_tags: , restrict mode: false, jsEngine: GRAALVM_COMPAT, api_autoload: true, C/C++ Standard: c++11, Compiler Flags: , Compiler Flags in list format: [], Clava Custom Resources: false, Disable Remote Dependencies: false, Weaved code foldername: woven, Disable Clava Info: true, Check C/CXX Syntax: false, Clean intermediate files: true, header includes: , parseIncludes: false, library includes: , systemIncludesThreshold: 1, Disable Weaving: false, Disable Code Generation: true, Generate Modified Code Only: false, Generate CMake Integration Helper Files: false, Copy files in sources: false, flatOutputFolder: false, libcCxxMode: Detect automatically (always uses base built-ins), ignoreHeaderIncludes: [], cudaGpuArch: sm_30, cudaPath: , parallelParsing: false, parsingNumThreads: 4, continueOnParsingErrors: false, customClangAstDumperExe: ]
 -==================================================-
  2. Initializing Interpreter
 -==================================================-
 -==================================================-
  3. Loading Weaver
 -==================================================-
Importing internal scripts:
  \_ larai/includes/scripts/dot.js
  \_ larai/includes/scripts/dwarvUtils.js
  \_ larai/includes/scripts/input.js
  \_ larai/includes/scripts/LaraObject.js
  \_ larai/includes/scripts/merge.js
  \_ larai/includes/scripts/namedArguments.js
  \_ larai/includes/scripts/output.js
  \_ larai/includes/scripts/select.js
  \_ larai/includes/scripts/toolExecution.js
  \_ larai/includes/scripts/utils.js
  \_ larai/includes/scripts/xilinx.js
  \_ larai/includes/scripts/Enum.js
  \_ lara/LaraCore.js
  \_ clava/js/autopar/Add_msgError.js
  \_ clava/js/autopar/allReplace.js
  \_ clava/js/autopar/GetLoopIndex.js
  \_ clava/js/autopar/orderedVarrefs3.js
  \_ clava/js/autopar/RemoveStruct.js
  \_ clava/js/autopar/SafeFunctionCalls.js
  \_ clava/js/autopar/SearchStruct.js
  \_ clava/js/DataHandler.js
  \_ clava/js/HDF5.js
  \_ clava/js/Types.js
  \_ clava/antarex/AntarexTest.js
java.lang.RuntimeException: Exception during interpretation
	at larai.LaraI.execPrivate(LaraI.java:269)
	at larai.LaraI.lambda$3(LaraI.java:221)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.lara.interpreter.exception.WeaverEngineException: exception when initializing the weaver
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:191)
	at larai.LaraI.interpret(LaraI.java:676)
	at larai.LaraI.execPrivate(LaraI.java:256)
	... 5 more
Caused by: pt.up.fe.specs.clang.codeparser.ClavaParserException: There are errors in the source code:
In file included from /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp:6:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/math.h:300:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/math.h:36:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:310:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/type_traits:420:
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cstddef:44:15: fatal error: 'stddef.h' file not found
#include_next <stddef.h>
              ^~~~~~~~~~
1 error generated.
Error while processing /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp.
In file included from /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp:6:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/math.h:300:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/math.h:36:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:310:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/type_traits:420:
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cstddef:44:15: fatal error: 'stddef.h' file not found
#include_next <stddef.h>
              ^~~~~~~~~~
1 error generated.
Error while processing /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp.

	at pt.up.fe.specs.clang.codeparser.ParallelCodeParser.parse(ParallelCodeParser.java:233)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.createApp(CxxWeaver.java:869)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.createApp(CxxWeaver.java:777)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.begin(CxxWeaver.java:508)
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:174)
	... 7 more
```

**Comment by joaobispo** [comment]
Hello @mingodad, thank you a lot for your feedback.

As an experiment I would ask you to try the following, could you please try to build the [ClangAstDumper](https://github.com/specs-feup/clava/tree/master/ClangAstDumper) project? This is a C++ project, and it creates the binary for the dumper.

First see if it can compile with the default options, and if it can, replace the file `/tmp/clang_ast_exe_mingo/clang_ast_v12.0.7` with the generated binary.

We are not currently supporting Ubuntu 18.04, only 20.04 and up, but during the next week I might be able to create a binary for Ubuntu 18.04 if this does not work.

**Comment by mingodad** [comment]
I just built the ClangAstDumper using netbeans insteado of the `make/cmake` files due to path/include/lib differences and I still need to add a wrapper to add my system include path to find `stddef.h`:
```
#!/bin/sh
args="$* -isystem /usr/lib/gcc/x86_64-linux-gnu/10/include"
#echo $args
$HOME/dev/c/A_programming-languages/clava/astdumper-nb/dist/Debug/GNU-Linux/astdumper-nb $args
```
But now it complains about :
```
 -==================================================-
  1. . LARA Options
 -==================================================-
Clava [aspect: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/lara/FullCallGraph.lara, main: , argv: , workspace: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp, workspace_extra: {}, output: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph, include: , autoimportjs: false, external_dependencies: [], tools: [ ] , report: [ ] , metrics: [ ] /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/metrics.json, loc: false, verbose: all, log: [ ] , javascript: true, debug: true, stack trace: true, bundle_tags: , restrict mode: false, jsEngine: GRAALVM_COMPAT, api_autoload: true, C/C++ Standard: c++11, Compiler Flags: , Compiler Flags in list format: [], Clava Custom Resources: false, Disable Remote Dependencies: false, Weaved code foldername: woven, Disable Clava Info: false, Check C/CXX Syntax: true, Clean intermediate files: true, header includes: , parseIncludes: false, library includes: , systemIncludesThreshold: 1, Disable Weaving: false, Disable Code Generation: true, Generate Modified Code Only: false, Generate CMake Integration Helper Files: false, Copy files in sources: false, flatOutputFolder: false, libcCxxMode: Detect automatically (always uses base built-ins), ignoreHeaderIncludes: [], cudaGpuArch: sm_30, cudaPath: , parallelParsing: false, parsingNumThreads: 4, continueOnParsingErrors: false, customClangAstDumperExe: ]
 -==================================================-
  2. Initializing Interpreter
 -==================================================-
 -==================================================-
  3. Loading Weaver
 -==================================================-
Importing internal scripts:
  \_ larai/includes/scripts/dot.js
  \_ larai/includes/scripts/dwarvUtils.js
  \_ larai/includes/scripts/input.js
  \_ larai/includes/scripts/LaraObject.js
  \_ larai/includes/scripts/merge.js
  \_ larai/includes/scripts/namedArguments.js
  \_ larai/includes/scripts/output.js
  \_ larai/includes/scripts/select.js
  \_ larai/includes/scripts/toolExecution.js
  \_ larai/includes/scripts/utils.js
  \_ larai/includes/scripts/xilinx.js
  \_ larai/includes/scripts/Enum.js
  \_ lara/LaraCore.js
  \_ clava/js/autopar/Add_msgError.js
  \_ clava/js/autopar/allReplace.js
  \_ clava/js/autopar/GetLoopIndex.js
  \_ clava/js/autopar/orderedVarrefs3.js
  \_ clava/js/autopar/RemoveStruct.js
  \_ clava/js/autopar/SafeFunctionCalls.js
  \_ clava/js/autopar/SearchStruct.js
  \_ clava/js/DataHandler.js
  \_ clava/js/HDF5.js
  \_ clava/js/Types.js
  \_ clava/antarex/AntarexTest.js
Found 1 source files
Parsing '/home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp' (1/1)
In file included from /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp:6:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/math.h:300:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/math.h:36:
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:321:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:322:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:323:9: error: no member named 'isfinite' in the global namespace
using ::isfinite;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:324:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:325:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:326:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:327:9: error: no member named 'isgreater' in the global namespace
using ::isgreater;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:328:9: error: no member named 'isgreaterequal' in the global namespace
using ::isgreaterequal;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:329:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:330:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:331:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:332:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:333:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:335:9: error: no member named 'float_t' in the global namespace
using ::float_t;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:336:9: error: no member named 'double_t' in the global namespace
using ::double_t;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:339:9: error: no member named 'abs' in the global namespace
using ::abs;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:342:9: error: no member named 'acos' in the global namespace
using ::acos;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:343:9: error: no member named 'acosf' in the global namespace
using ::acosf;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:344:9: error: no member named 'asin' in the global namespace
using ::asin;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
No parser defined for attribute 'BuiltinAttr', using generic attribute parser with no arguments
Error while running DumpAstAction (return code 1)
20 errors generated.
Error while processing /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp.
[ClavaMetrics] Code to AST: 379ms
java.lang.RuntimeException: Exception during interpretation
	at larai.LaraI.execPrivate(LaraI.java:269)
	at larai.LaraI.lambda$3(LaraI.java:221)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.lara.interpreter.exception.WeaverEngineException: exception when initializing the weaver
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:191)
	at larai.LaraI.interpret(LaraI.java:676)
	at larai.LaraI.execPrivate(LaraI.java:256)
	... 5 more
Caused by: pt.up.fe.specs.clang.codeparser.ClavaParserException: There are errors in the source code:
In file included from /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp:6:
In file included from /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/math.h:300:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/math.h:36:
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:321:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:322:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:323:9: error: no member named 'isfinite' in the global namespace
using ::isfinite;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:324:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:325:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:326:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:327:9: error: no member named 'isgreater' in the global namespace
using ::isgreater;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:328:9: error: no member named 'isgreaterequal' in the global namespace
using ::isgreaterequal;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:329:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:330:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:331:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:332:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:333:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:335:9: error: no member named 'float_t' in the global namespace
using ::float_t;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:336:9: error: no member named 'double_t' in the global namespace
using ::double_t;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:339:9: error: no member named 'abs' in the global namespace
using ::abs;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:342:9: error: no member named 'acos' in the global namespace
using ::acos;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:343:9: error: no member named 'acosf' in the global namespace
using ::acosf;
      ~~^
/tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0/cmath:344:9: error: no member named 'asin' in the global namespace
using ::asin;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Error while processing /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp.

	at pt.up.fe.specs.clang.codeparser.ParallelCodeParser.parse(ParallelCodeParser.java:233)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.createApp(CxxWeaver.java:869)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.createApp(CxxWeaver.java:777)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.begin(CxxWeaver.java:508)
	at org.lara.interpreter.weaver.MasterWeaver.begin(MasterWeaver.java:174)
	... 7 more
*Application Stopped*
```

**Comment by mingodad** [comment]
Also I found a bug where in the lara editor if we press `CTRL-z` the content of the editor is wiped.

**Comment by mingodad** [comment]
After dump the command line for `ClangAstDumper` and testing different combinations of `-isystem` includes this one was the one that could process `specs-lara/Examples/CallGraph/src/CallGraph.cpp` prolerly:
```
astdumper-nb/dist/Debug/GNU-Linux/astdumper-nb \
	/home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp \
	-id=1 -system-header-threshold=1 -- -std=c++11 \
	-isystem /usr/lib/gcc/x86_64-linux-gnu/10/include \
	-isystem /usr/include/linux \
	-I/home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src \
	-Wno-unknown-pragmas -I/home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src

#	-isystem /tmp/clang_ast_exe_mingo/clang_includes/0-builtin_includes \
#	-isystem /tmp/clang_ast_exe_mingo/clang_includes/1-libcxx_12.0.0 \
```

**Comment by joaobispo** [comment]
The problem may have to do with the built-in libraries that are automatically included. In order to run Clava out-of-the-box in systems that usually do not have C/C++ include headers, some files are automatically included. However, these header files might not be compatible with some systems.

Could you tweak the option `libc/libc++ mode`, for instance choosing `Nothing`, to see if this solves the problem?


Using the CLI:

`-lib "Nothing (i.e. use system libs)"`

Using the GUI:

![image](https://user-images.githubusercontent.com/5724365/208409943-25dff10d-c352-4a24-bcf3-0abc5234cc13.png)

**Comment by mingodad** [comment]
With your last suggestion and also `System Includes = /usr/lib/gcc/x86_64-linux-gnu/10/include` then it works.
```
 -==================================================-
  1. . LARA Options
 -==================================================-
Clava [aspect: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/lara/FullCallGraph.lara, main: , argv: , workspace: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/src/CallGraph.cpp, workspace_extra: {}, output: /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph, include: , autoimportjs: false, external_dependencies: [], tools: [ ] , report: [ ] , metrics: [ ] /home/mingo/dev/c/A_programming-languages/clava/specs-lara/Examples/CallGraph/metrics.json, loc: false, verbose: all, log: [ ] , javascript: true, debug: true, stack trace: true, bundle_tags: , restrict mode: false, jsEngine: GRAALVM_COMPAT, api_autoload: true, C/C++ Standard: c++11, Compiler Flags: , Compiler Flags in list format: [], Clava Custom Resources: false, Disable Remote Dependencies: false, Weaved code foldername: woven, Disable Clava Info: false, Check C/CXX Syntax: true, Clean intermediate files: true, header includes: , parseIncludes: false, library includes: /usr/lib/gcc/x86_64-linux-gnu/10/include, systemIncludesThreshold: 1, Disable Weaving: false, Disable Code Generation: true, Generate Modified Code Only: false, Generate CMake Integration Helper Files: false, Copy files in sources: false, flatOutputFolder: false, libcCxxMode: Nothing (i.e. use system libs), ignoreHeaderIncludes: [], cudaGpuArch: sm_30, cudaPath: , parallelParsing: false, parsingNumThreads: 4, continueOnParsingErrors: false, customClangAstDumperExe: ]
```

**Comment by mingodad** [comment]
Should be a way to set those values system wide because needing to do it on every project is a bit cumbersome.

**Comment by joaobispo** [comment]
There is a new version of Clava available that supports setting default values system-wide, you can either download [clava.zip](http://specs.fe.up.pt/tools/clava.zip), or use the installation/update script [clava-update](specs.fe.up.pt/tools/clava/clava-update).

When running a configuration for the first time after the update, there should be a message similar to this:

```
Options file 'Clava_system_options.xml' not found near JAR, creating empty file:<some path...>/Clava_system_options.xml
This file can also be on the working directory.
```

To use default values, create a configuration file using the GUI with the default values you want, and copy that the file to the path that appears in the message, overwriting that file.

If the value is redefined in the local options file, it will overwrite the default value.

**Comment by joaobispo** [comment]
Going to close this issue as solved.
