### ISSUE TITLE
Friend declarations not implemented?

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#14]
Clava compiling this code:

```
class Cat {
};

class Dog {
  friend class Cat;
};
```

Results in this clava error message:
```
--- AST parsing report ---
getCode() not implemented for NullNode node: NullDecl [context: [arguments: {}, idGenerator: pt.up.fe.specs.clava.context.ClavaIdGenerator@faa2af8, factory: pt.up.fe.specs.clava.context.ClavaFactory@6830cce8, metrics: pt.up.fe.specs.clava.context.ClavaMetrics@7b2e5610, cachedFilepaths: pt.up.fe.specs.util.utilities.CachedItems@1d371609], id: decl_1, location: <Invalid Range>]
getCode() not implemented for NullNode node: NullDecl [context: [arguments: {}, idGenerator: pt.up.fe.specs.clava.context.ClavaIdGenerator@faa2af8, factory: pt.up.fe.specs.clava.context.ClavaFactory@6830cce8, metrics: pt.up.fe.specs.clava.context.ClavaMetrics@7b2e5610, cachedFilepaths: pt.up.fe.specs.util.utilities.CachedItems@1d371609], id: decl_1, location: <Invalid Range>]
Last exception type: class pt.up.fe.specs.util.exceptions.NotImplementedException
Last exception type: class java.lang.RuntimeException
Exception in thread "main" java.lang.RuntimeException: 
 During LARA Interpreter execution 
  
   when closing the weaver
    Not yet implemented in class 'pt.up.fe.specs.clava.ast.decl.NullDecl'
   Not yet implemented in class 'pt.up.fe.specs.clava.ast.decl.NullDecl'
	at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(LARAExceptionBuilder.java:164)
	at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(BaseException.java:101)
	at larai.LaraI.prettyRuntimeException(LaraI.java:436)
	at larai.LaraI.execPrivate(LaraI.java:358)
	at larai.LaraI.lambda$3(LaraI.java:274)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: 
 when closing the weaver
  Not yet implemented in class 'pt.up.fe.specs.clava.ast.decl.NullDecl'
	at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(LARAExceptionBuilder.java:164)
	at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(BaseException.java:101)
	at larai.LaraI.prettyRuntimeException(LaraI.java:436)
	at larai.LaraI.treatExceptionInInterpreter(LaraI.java:394)
	at larai.LaraI.execPrivate(LaraI.java:233)
	at larai.LaraI.execPrivate(LaraI.java:336)
	... 5 more
Caused by: pt.up.fe.specs.util.exceptions.NotImplementedException: Not yet implemented in class 'pt.up.fe.specs.clava.ast.decl.NullDecl'
	at pt.up.fe.specs.clava.utils.NullNode.getNullCode(NullNode.java:37)
	at pt.up.fe.specs.clava.ast.decl.NullDecl.getCode(NullDecl.java:41)
	at pt.up.fe.specs.clava.ast.decl.FriendDecl.getCode(FriendDecl.java:57)
	at pt.up.fe.specs.clava.ast.decl.RecordDecl.lambda$4(RecordDecl.java:208)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at pt.up.fe.specs.clava.ast.decl.RecordDecl.getDefinitionCode(RecordDecl.java:209)
	at pt.up.fe.specs.clava.ast.decl.RecordDecl.getCode(RecordDecl.java:177)
	at pt.up.fe.specs.clava.ast.decl.CXXRecordDecl.getCode(CXXRecordDecl.java:110)
	at pt.up.fe.specs.clava.ast.extra.TranslationUnit.getChildCode(TranslationUnit.java:492)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at pt.up.fe.specs.clava.ast.extra.TranslationUnit.getCode(TranslationUnit.java:399)
	at pt.up.fe.specs.clava.ast.extra.App.getTuCode(App.java:485)
	at pt.up.fe.specs.clava.ast.extra.App.getCode(App.java:461)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.writeCode(CxxWeaver.java:1257)
	at pt.up.fe.specs.clava.weaver.CxxWeaver.close(CxxWeaver.java:1087)
	at org.lara.interpreter.weaver.MasterWeaver.close(MasterWeaver.java:663)
	at larai.LaraI.interpret(LaraI.java:635)
	at larai.LaraI.execPrivate(LaraI.java:220)
	... 6 more
```

Once one removes the friend statement no error is produced.

**Comment by joaobispo** [comment]
The Clang dumper was not providing information when the friend was a type, this has been fixed.

**Comment by ppietrasa** [comment]
It helped. Thank you!
