### ISSUE TITLE
"Could not map classname 'GCCAsmStmt' to a ClavaNode class" on invocation of FD_ZERO

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#15]
The following code:

```
#include <sys/select.h>

int main(int argc, char *argv[]){
   fd_set someFd;
   FD_ZERO(&someFd);
   //FD_SET(0, &someFd);
   return 0;
}
```

results in:
```

Problems while parsing '<StmtData>' -> org.suikasoft.jOptions.streamparser.LineStreamParser.parse(LineStreamParser.java:92)

Exception message: [RuntimeException] Could not map classname 'GCCAsmStmt' to a ClavaNode class

Stack Trace:
--------------
pt.up.fe.specs.clava.utils.ClassesService.discoverClass(ClassesService.java:145)
pt.up.fe.specs.clava.utils.ClassesService.getClass(ClassesService.java:89)
pt.up.fe.specs.clava.utils.ClassesService.getClavaClass(ClassesService.java:62)
pt.up.fe.specs.clang.parsers.NodeDataParser.parseNodeData(NodeDataParser.java:287)
pt.up.fe.specs.clang.parsers.NodeDataParser.parseNodeData(NodeDataParser.java:258)
pt.up.fe.specs.clang.parsers.data.StmtDataParser.parseStmtData(StmtDataParser.java:36)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
pt.up.fe.specs.clang.parsers.NodeDataParser.lambda$2(NodeDataParser.java:194)
pt.up.fe.specs.clang.parsers.NodeDataParser.parseNodeDataTop(NodeDataParser.java:242)
pt.up.fe.specs.clang.parsers.NodeDataParser.lambda$0(NodeDataParser.java:136)
org.suikasoft.jOptions.streamparser.GenericLineStreamWorker.apply(GenericLineStreamWorker.java:47)
org.suikasoft.jOptions.streamparser.GenericLineStreamParser.parse(GenericLineStreamParser.java:78)
org.suikasoft.jOptions.streamparser.LineStreamParser.parse(LineStreamParser.java:90)
org.suikasoft.jOptions.streamparser.LineStreamParser.parse(LineStreamParser.java:65)
pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.processStdErr(AstDumpParser.java:422)
pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.lambda$2(AstDumpParser.java:345)
pt.up.fe.specs.util.SpecsSystem.lambda$4(SpecsSystem.java:360)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)
--------------

Problems while parsing '<Id to Class Map>' -> org.suikasoft.jOptions.streamparser.LineStreamParser.parse(LineStreamParser.java:92)

Exception message: [RuntimeException] No ClavaData/DataStore for node '0x55a565762af8_1' (classname: GCCAsmStmt), data dumper is not being called (linestream index '1575')

Stack Trace:
--------------
pt.up.fe.specs.clang.parsers.ClavaNodeParser.parseNode(ClavaNodeParser.java:171)
pt.up.fe.specs.clang.parsers.ClavaNodeParser.apply(ClavaNodeParser.java:108)
pt.up.fe.specs.clang.parsers.ClavaNodeParser.apply(ClavaNodeParser.java:1)
org.suikasoft.jOptions.streamparser.GenericLineStreamParser.parse(GenericLineStreamParser.java:78)
org.suikasoft.jOptions.streamparser.LineStreamParser.parse(LineStreamParser.java:90)
org.suikasoft.jOptions.streamparser.LineStreamParser.parse(LineStreamParser.java:65)
pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.processStdErr(AstDumpParser.java:422)
pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.lambda$2(AstDumpParser.java:345)
pt.up.fe.specs.util.SpecsSystem.lambda$4(SpecsSystem.java:360)
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base/java.lang.Thread.run(Thread.java:834)
--------------

Exception while waiting for output/error streams: java.lang.RuntimeException: Error while parsing output of Clang AST dumper
Last exception type: class java.lang.RuntimeException
Last exception type: class java.lang.RuntimeException
Exception in thread "main" java.lang.RuntimeException: 
 During LARA Interpreter execution 
  
   when initializing the weaver
    Error while running Clang AST dumper
     Exception while processing the output streams
      java.lang.RuntimeException: Error while parsing output of Clang AST dumper
       Error while parsing output of Clang AST dumper
        Did not find ClavaNode for child with index '1' and id '0x55a565762af8_1' when parsing CompoundStmt -> CompoundStmt [context: [arguments: {}, factory: pt.up.fe.specs.clava.context.ClavaFactory@77638370, metrics: pt.up.fe.specs.clava.context.ClavaMetrics@41548055, cachedFilepaths: pt.up.fe.specs.util.utilities.CachedItems@1c6f55e7], id: 0x55a565762bc0_1, location: helloworld.cpp:5:4, isMacro: true, isInSystemHeader: false]
   Error while running Clang AST dumper
    Exception while processing the output streams
     java.lang.RuntimeException: Error while parsing output of Clang AST dumper
      Error while parsing output of Clang AST dumper
       Did not find ClavaNode for child with index '1' and id '0x55a565762af8_1' when parsing CompoundStmt -> CompoundStmt [context: [arguments: {}, factory: pt.up.fe.specs.clava.context.ClavaFactory@77638370, metrics: pt.up.fe.specs.clava.context.ClavaMetrics@41548055, cachedFilepaths: pt.up.fe.specs.util.utilities.CachedItems@1c6f55e7], id: 0x55a565762bc0_1, location: helloworld.cpp:5:4, isMacro: true, isInSystemHeader: false]
	at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(LARAExceptionBuilder.java:164)
	at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(BaseException.java:101)
	at larai.LaraI.prettyRuntimeException(LaraI.java:436)
	at larai.LaraI.execPrivate(LaraI.java:358)
	at larai.LaraI.lambda$3(LaraI.java:274)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: 
 when initializing the weaver
  Error while running Clang AST dumper
   Exception while processing the output streams
    java.lang.RuntimeException: Error while parsing output of Clang AST dumper
     Error while parsing output of Clang AST dumper
      Did not find ClavaNode for child with index '1' and id '0x55a565762af8_1' when parsing CompoundStmt -> CompoundStmt [context: [arguments: {}, factory: pt.up.fe.specs.clava.context.ClavaFactory@77638370, metrics: pt.up.fe.specs.clava.context.ClavaMetrics@41548055, cachedFilepaths: pt.up.fe.specs.util.utilities.CachedItems@1c6f55e7], id: 0x55a565762bc0_1, location: helloworld.cpp:5:4, isMacro: true, isInSystemHeader: false]
	at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(LARAExceptionBuilder.java:164)
	at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(BaseException.java:101)
	at larai.LaraI.prettyRuntimeException(LaraI.java:436)
	at larai.LaraI.treatExceptionInInterpreter(LaraI.java:394)
	at larai.LaraI.execPrivate(LaraI.java:233)
	at larai.LaraI.execPrivate(LaraI.java:336)
	... 5 more
Caused by: java.lang.RuntimeException: Error while running Clang AST dumper
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.parsePrivate(AstDumpParser.java:375)
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.parse(AstDumpParser.java:162)
	at pt.up.fe.specs.clang.codeparser.ParallelCodeParser.parseSource(ParallelCodeParser.java:373)
	at pt.up.fe.specs.clang.codeparser.ParallelCodeParser.lambda$3(ParallelCodeParser.java:159)
	... 4 more
Caused by: java.lang.RuntimeException: Exception while processing the output streams
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.lambda$3(AstDumpParser.java:359)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.parsePrivate(AstDumpParser.java:358)
	... 7 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error while parsing output of Clang AST dumper
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at pt.up.fe.specs.util.SpecsSystem.executeProcess(SpecsSystem.java:445)
	at pt.up.fe.specs.util.SpecsSystem.runProcess(SpecsSystem.java:375)
	at pt.up.fe.specs.util.SpecsSystem.runProcess(SpecsSystem.java:327)
	at pt.up.fe.specs.util.SpecsSystem.runProcess(SpecsSystem.java:321)
	at pt.up.fe.specs.util.SpecsSystem.runProcess(SpecsSystem.java:220)
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.parsePrivate(AstDumpParser.java:339)
	... 7 more
Caused by: java.lang.RuntimeException: Error while parsing output of Clang AST dumper
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.processStdErr(AstDumpParser.java:441)
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.lambda$2(AstDumpParser.java:345)
	at pt.up.fe.specs.util.SpecsSystem.lambda$4(SpecsSystem.java:360)
	... 4 more
Caused by: java.lang.NullPointerException: Did not find ClavaNode for child with index '1' and id '0x55a565762af8_1' when parsing CompoundStmt -> CompoundStmt [context: [arguments: {}, factory: pt.up.fe.specs.clava.context.ClavaFactory@77638370, metrics: pt.up.fe.specs.clava.context.ClavaMetrics@41548055, cachedFilepaths: pt.up.fe.specs.util.utilities.CachedItems@1c6f55e7], id: 0x55a565762bc0_1, location: helloworld.cpp:5:4, isMacro: true, isInSystemHeader: false]
	at pt.up.fe.specs.util.SpecsCheck.checkNotNull(SpecsCheck.java:39)
	at pt.up.fe.specs.clang.parsers.ClavaNodeParser.lambda$0(ClavaNodeParser.java:239)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at pt.up.fe.specs.clang.parsers.ClavaNodeParser.close(ClavaNodeParser.java:347)
	at pt.up.fe.specs.clang.parsers.ClavaNodeParser.close(ClavaNodeParser.java:1)
	at org.suikasoft.jOptions.streamparser.GenericLineStreamParser.close(GenericLineStreamParser.java:96)
	at pt.up.fe.specs.clang.codeparser.clangparser.AstDumpParser.processStdErr(AstDumpParser.java:430)
	... 6 more
```

This is due to the call to FD_ZERO. Interestingly,  invoking other FD_* functions from "sys/select.h" works without an error.

Indeed, the FD_ZERO is a bit special on my system and maps to:
```
# define __FD_ZERO(fdsp) \
  do {                                                                        \
    int __d0, __d1;                                                           \
    __asm__ __volatile__ ("cld; rep; " __FD_ZERO_STOS                         \
                          : "=c" (__d0), "=D" (__d1)                          \
                          : "a" (0), "0" (sizeof (fd_set)                     \
                                          / sizeof (__fd_mask)),              \
                            "1" (&__FDS_BITS (fdsp)[0])                       \
                          : "memory");                                        \
  } while (0)
```

others are just plain C.

**Comment by joaobispo** [comment]
GCC-style inline assembly was not implemented, now it should work.

**Comment by joaobispo** [comment]
Please check if the issue is solved, so that it can be closed.

**Comment by joaobispo** [comment]
I think it had to do with the code generation of GCCAsmStmt. I've just pushed a fix, please try again.

**Comment by ppietrasa** [comment]
Closing. I confirm it is working correct now.  Thank  you!
