### ISSUE TITLE
StatementDecomposer fails by not finding method replaceWith([Ljava.lang.Object;)

### ISSUE THREAD

**Issue by tiagolascasas** [specs-feup/clava#168]
Error message:

```
StatementDecomposer: Error: Could not find method "declStmt([Lpt.up.fe.specs.clava.weaver.joinpoints.CxxVardecl;)" on class "class pt.up.fe.specs.clava.weaver.importable.AstFactory". Possible matches:
  public static pt.up.fe.specs.clava.weaver.abstracts.joinpoints.ADeclStmt pt.up.fe.specs.clava.weaver.importable.AstFactory.declStmt(pt.up.fe.specs.clava.weaver.abstracts.joinpoints.ADecl[])

Execution failed.
Error: Could not find method "replaceWith([Ljava.lang.Object;)" on class "class pt.up.fe.specs.clava.weaver.joinpoints.CxxExprStmt". Possible matches:
  public final java.lang.Object pt.up.fe.specs.clava.weaver.abstracts.joinpoints.AJoinPoint.replaceWith(pt.up.fe.specs.clava.weaver.abstracts.joinpoints.AJoinPoint)
  public final java.lang.Object pt.up.fe.specs.clava.weaver.abstracts.joinpoints.AJoinPoint.replaceWith(java.lang.String)
  public final java.lang.Object pt.up.fe.specs.clava.weaver.abstracts.joinpoints.AJoinPoint.replaceWith(pt.up.fe.specs.clava.weaver.abstracts.joinpoints.AJoinPoint[])

    at ExprStmt.replaceWith (file:///home/tls/Dev/clava-js-code-transformations/node_modules/@specs-feup/clava/api/Joinpoints.js:318:61)
    at StatementDecomposer.decomposeAndReplace (file:///home/tls/Dev/clava-js-code-transformations/node_modules/@specs-feup/clava/api/clava/code/StatementDecomposer.js:51:15)
    at file:///home/tls/Dev/clava-js-code-transformations/dist/test/TestStructDecomp.js:11:12
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async Weaver.executeScript (file:///home/tls/Dev/clava-js-code-transformations/node_modules/@specs-feup/lara/code/Weaver.js:120:13)
    at async file:///home/tls/Dev/clava-js-code-transformations/node_modules/@specs-feup/lara/code/Weaver.js:195:9
```

Replicate using Clava-JS with the following script:

```TS
import Query from "@specs-feup/lara/api/weaver/Query.js";
import { FunctionJp, Statement } from "@specs-feup/clava/api/Joinpoints.js";
import StatementDecomposer from "@specs-feup/clava/api/clava/code/StatementDecomposer.js";
import NormalizeToSubset from "@specs-feup/clava/api/clava/opt/NormalizeToSubset.js";

for (const fun of Query.search(FunctionJp, { "isImplementation": true })) {
    const body = fun.body;
    NormalizeToSubset(body, { simplifyLoops: { forToWhile: false } });
}

const decomp = new StatementDecomposer();
for (var stmt of Query.search(Statement, { isInsideHeader: false })) {
    decomp.decomposeAndReplace(stmt);
}
```

And this input:

```C++
#include <stdio.h>

float buzz(int *A, double *B, char C[])
{
    for (int i = 0; i < 100; i++)
    {
        C[i] = 0;
    }
    int *X;
    for (int i = 0; i < 100; i++)
    {
        C[i] = C[i] + 1;
        for (int j = 0; j < 100; j++)
        {
            if (C[i] > 0)
                return 0.3;
            C[j] = C[j] + 2;
            for (int k = 0; k < 100; k++)
            {
                C[k] = C[k] + 3;
                if (C[k] > 0)
                {

                    return 0.4;
                }
                for (int l = 0; l < 100; l++)
                {
                    C[l] = C[l] + 4;
                }
            }
        }
    }
    return 0.6;
}
```

**Comment by joaobispo** [comment]
We must always be careful in the Node.JS <-> Java interface, and we should convention simple rules that avoid certain cases.

In this case, Java methods with varargs should not be allowed to interface directly with Node.JS, instead methods should always use Object[] as parameters, if an array is needed. In the Java side the necessary checks should then be done.

The weaver generator has been changed to accomodate this convention, as well as several Java methods that are called from Node.JS.

**Comment by joaobispo** [comment]
There is an additional issue, when using imports such as `import Query from "@specs-feup/lara/api/weaver/Query.js";` from Java mode, instead of node mode, the folder node_modules is not being correctly found by GraalVM.

**Comment by joaobispo** [comment]
Closed by [PR 174](https://github.com/specs-feup/clava/pull/174)
