### ISSUE TITLE
ClavaJoinPoints.functionDecl fails when creating a function with no parameters

### ISSUE THREAD

**Issue by tiagolascasas** [specs-feup/clava#172]
Error:

```
Execution failed.
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at unwrapJoinPoint (file:///home/tls/clava-workspace/node_modules/@specs-feup/lara/api/LaraJoinPoint.js:119:54)
    at ClavaJoinPoints.functionDecl (file:///home/tls/clava-workspace/node_modules/@specs-feup/clava/api/clava/ClavaJoinPoints.js:216:113)
    at file:///home/tls/clava-workspace/clava-js-code-transformations/dist/test/TestFunctionDecl.js:16:30
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async Weaver.executeScript (file:///home/tls/clava-workspace/node_modules/@specs-feup/lara/code/Weaver.js:120:13)
    at async file:///home/tls/clava-workspace/node_modules/@specs-feup/lara/code/Weaver.js:195:9
```

Replicate with:
```ts
import ClavaJoinPoints from "@specs-feup/clava/api/clava/ClavaJoinPoints.js";
import Clava from "@specs-feup/clava/api/clava/Clava.js";
import { Param } from "@specs-feup/clava/api/Joinpoints.js";

Clava.pushAst(ClavaJoinPoints.program());
const fileJp = ClavaJoinPoints.file("foo.c");
Clava.addFile(fileJp);

// Creating a function with parameters works
const params = [
    ClavaJoinPoints.param("a", ClavaJoinPoints.type("int")),
    ClavaJoinPoints.param("b", ClavaJoinPoints.type("int")),
]
const ret = ClavaJoinPoints.type("void");
const fun = ClavaJoinPoints.functionDecl("foo", ret, ...params);
fileJp.insertEnd(fun);

// But creating one without doesn't
const params2: Param[] = [];
const ret2 = ClavaJoinPoints.type("void");
const fun2 = ClavaJoinPoints.functionDecl("bar", ret2, ...params2);
// Alternatively, it also fails if the third arg is not passed
//const fun2 = ClavaJoinPoints.functionDecl("bar", ret2);
fileJp.insertEnd(fun2);
```

**Comment by joaobispo** [comment]
TypeScript code in the lara-framework still assumed Java methods with varargs could be called from Node.JS, this has been fixed.
