### ISSUE TITLE
Dynamic cast not working

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#25]
C++ input:
```
class BaseKlass {
   public:
   virtual ~BaseKlass() {}
};

class DerivedKlass : BaseKlass {
   public:
      int f(int x) { return x + 1; }
};

BaseKlass* base = new BaseKlass();
DerivedKlass* derived = dynamic_cast<DerivedKlass*>(base);
```

A LARA that touches the input code:
```
aspectdef TouchMeAspect
  select vardecl end
  apply
    setName('a_' + $vardecl.name);
  end
end
```

Transpiling leads to the NullPointerException:
```
--- AST parsing report ---
Last exception type: class java.lang.NullPointerException
Last exception type: class java.lang.RuntimeException
Exception in thread "main" java.lang.RuntimeException:
 During LARA Interpreter execution

   when closing the weaver
    caused by NullPointerException
   caused by NullPointerException
        at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(Unknown Source)
        at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(Unknown Source)
        at larai.LaraI.prettyRuntimeException(Unknown Source)
        at larai.LaraI.execPrivate(Unknown Source)
        at larai.LaraI.lambda$exec$2(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException:
 when closing the weaver
  caused by NullPointerException
        at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(Unknown Source)
        at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(Unknown Source)
        at larai.LaraI.prettyRuntimeException(Unknown Source)
        at larai.LaraI.treatExceptionInInterpreter(Unknown Source)
        at larai.LaraI.execPrivate(Unknown Source)
        ... 6 more
Caused by: java.lang.NullPointerException
        at pt.up.fe.specs.clava.ast.expr.CXXNamedCastExpr.getCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.decl.enums.InitializationStyle.cinitCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.decl.enums.InitializationStyle.getCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.decl.VarDecl.getInitializationCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.decl.VarDecl.getCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.stmt.DeclStmt.getCodeDeclList(Unknown Source)
        at pt.up.fe.specs.clava.ast.stmt.DeclStmt.getCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.extra.TranslationUnit.getChildCode(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at pt.up.fe.specs.clava.ast.extra.TranslationUnit.getCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.extra.App.getTuCode(Unknown Source)
        at pt.up.fe.specs.clava.ast.extra.App.getCode(Unknown Source)
        at pt.up.fe.specs.clava.weaver.CxxWeaver.writeCode(Unknown Source)
        at pt.up.fe.specs.clava.weaver.CxxWeaver.close(Unknown Source)
        at org.lara.interpreter.weaver.MasterWeaver.close(Unknown Source)
        at larai.LaraI.interpret(Unknown Source)
        ... 7 more
```

**Comment by ppietrasa** [comment]
A hint.

In `ClavaAst/src/pt/up/fe/specs/clava/ast/expr/CXXNamedCastExpr.java:76`
```
 [..]
 75         // String typeCode = cxxNamedCastExprdata.getTypeAsWritten();
 76         String typeCode = get(TYPE_AS_WRITTEN).getCode(this);
 77         if (typeCode.equals("_Bool") && getAncestorTry(TranslationUnit.class)
 [..]
```
the `get(TYPE_AS_WRITTEN)` returns `null`.

**Comment by joaobispo** [comment]
Thanks for the tip. The problem had to do with the dumper not properly dumping information about the dynamic cast, it should now be fixed.

**Comment by ppietrasa** [comment]
Thanks! It works fine now.
