### ISSUE TITLE
Could not evaluate JavaScript code during LARA Interpreter execution (with self build clava!)

### ISSUE THREAD

**Issue by ppietrasa** [specs-feup/clava#8]
This happens only if I use the self-build clava and does not happen with the pre-build version.
So this may be no-issue, but perhaps you may have an idea or be able to help?

I build the clava myself. This seemed to work fine, except the issue with the jar file #6 . To create the final jar I modified the generated jar.xml in place (as described in issue #6) and produced the jar so:

$ ant jar.xml create_jar

The resulting ClavaWeaver seemed to work (at least `--help` did work) so I proceeded to weaving and am getting these errors:

```
Running on: Linux
Reading: /home/piotr/work/ems/obfu.lara
Parse Successful!
 -==================================================-
  2. Organizing Aspects
 -==================================================-
Organized!
 -==================================================-
  3. Creating Aspect-IR
 -==================================================-
Created!
Processed 38 tokens from the LARA file.
 -==================================================-
  1. . Loading Aspect-IR
 -==================================================-
Last exception type: class java.lang.RuntimeException
Last exception type: class java.lang.RuntimeException
Exception in thread "main" java.lang.RuntimeException: 
 During LARA Interpreter execution 
  
   During LARA Interpreter execution 
    Could not evaluate JavaScript code
     Could not find option with name js.script-engine-global-scope-import.
   Could not evaluate JavaScript code
    Could not find option with name js.script-engine-global-scope-import.
        at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(Unknown Source)
        at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(Unknown Source)
        at larai.LaraI.prettyRuntimeException(Unknown Source)
        at larai.LaraI.execPrivate(Unknown Source)
        at larai.LaraI.lambda$exec$2(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: 
 During LARA Interpreter execution 
  Could not evaluate JavaScript code
   Could not find option with name js.script-engine-global-scope-import.
        at pt.up.fe.specs.tools.lara.exception.LARAExceptionBuilder.getRuntimeException(Unknown Source)
        at pt.up.fe.specs.tools.lara.exception.BaseException.generateRuntimeException(Unknown Source)
        at larai.LaraI.prettyRuntimeException(Unknown Source)
        at larai.LaraI.treatExceptionInInterpreter(Unknown Source)
        at larai.LaraI.execPrivate(Unknown Source)
        ... 6 more
Caused by: java.lang.RuntimeException: Could not evaluate JavaScript code
        at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine.eval(Unknown Source)
        at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine.<init>(Unknown Source)
        at pt.up.fe.specs.jsengine.JsEngineType.newEngine(Unknown Source)
        at larai.LaraI.createJsEngine(Unknown Source)
        at larai.LaraI.interpret(Unknown Source)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: Could not find option with name js.script-engine-global-scope-import.
        at com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:228)
        at com.oracle.truffle.polyglot.PolyglotContextConfig.findLanguageForOption(PolyglotContextConfig.java:210)
        at com.oracle.truffle.polyglot.PolyglotContextConfig.<init>(PolyglotContextConfig.java:117)
        at com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1163)
        at org.graalvm.polyglot.Context$Builder.build(Context.java:1398)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.createDefaultContext(GraalJSScriptEngine.java:256)
        at com.oracle.truffle.js.scriptengine.GraalJSBindings.initContext(GraalJSBindings.java:82)
        at com.oracle.truffle.js.scriptengine.GraalJSBindings.requireContext(GraalJSBindings.java:77)
        at com.oracle.truffle.js.scriptengine.GraalJSBindings.getContext(GraalJSBindings.java:145)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.getPolyglotContext(GraalJSScriptEngine.java:296)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.getPolyglotContext(GraalJSScriptEngine.java:287)
        ... 12 more

```

What could have gone wrong?

**Comment by joaobispo** [comment]
The problem is related to the way eclipse-build packages the JAR. The technique it uses (putting all files inside the same JAR) breaks a library used by Clava (i.e., GraalVM).

The pre-built version uses a different packaging method, where the JAR only contains the files of the ClavaWeaver project and other dependencies from Eclipse projects and puts the JARs of external libraries in a separate subfolder (i.e., ClavaWeaver_lib). 

I've updated eclipse-build in order to support a new option --jar, which can be used to determine the kind of JAR packaging to use. I've also updated the ClavaWeaver build configuration, to use this new option and the subfolder packaging.

Please try running eclipse-build again to see if the problem is solved.

**Comment by ppietrasa** [comment]
Thank you very much for your supoprt!

I issued:
`$ java -jar eclipse-build.jar --config https://raw.githubusercontent.com/specs-feup/clava/master/ClavaWeaver/eclipse.build`

The ClavaWeaver.jar got smaller in size, the ClavaWever_lib with external lib-jars created alongside, and the JS evaluation errors have indeed disappeared :-)
So I am OK with closing this.

However, I also tried passing the "subfolder" argument explicitly:
```
$ java -jar eclipse-build.jar --jar SUBFOLDER --config https://raw.githubusercontent.com/specs-feup/clava/master/ClavaWeaver/eclipse.build
Downloading 'eclipse.build' to '/tmp/tmp_piotr/specs_git_repos'...
Exception in thread "main" java.lang.IllegalArgumentException: Attempting to add value already in PassData: jarType (JarType = Optional[REPACK])
	at pt.up.fe.specs.util.SpecsCheck.checkArgument(SpecsCheck.java:33)
	at org.suikasoft.jOptions.Interfaces.DataStore.add(DataStore.java:196)
	at pt.up.fe.specs.eclipsebuild.option.EclipseBuildArgumentsParser.lambda$2(EclipseBuildArgumentsParser.java:95)
	at pt.up.fe.specs.eclipsebuild.option.EclipseBuildArgumentsParser.parseArguments(EclipseBuildArgumentsParser.java:173)
	at pt.up.fe.specs.eclipsebuild.EclipseBuildLauncher.execute(EclipseBuildLauncher.java:54)
	at pt.up.fe.specs.eclipsebuild.EclipseBuildLauncher.main(EclipseBuildLauncher.java:46)
```

**Comment by joaobispo** [comment]
Thank you for noticing this, this is happening because the file eclipse.build already sets the flag `--jar`. 

I've updated eclipse-build to allow duplicated flags, successive instances of the same flag will now overwrite the previous value. This means that in the example you provided, the value of `--jar SUBFOLDER` will be overwritten by the value in the config file.

**Comment by ppietrasa** [comment]
Thanks! Closing..
